### ISSUE TITLE
The situation about yout checkpoint (epoch_62.pth and current.pth)

### ISSUE THREAD

**Issue by red0orange** [alinasarmiento/pytorch_contactnet#1]
Thank you for your development! 
Now I can use your code, but I want to know if your checkpoint can be used in your env. (I use it in my real scene and I don't want to try it in ShapeNet test data).

**Comment by alinasarmiento** [comment]
Hi, thanks for the question. I have updated the main branch with a better script for loading the checkpoint I have, and it should work on any pointcloud of shape (Nx3), not just on ACRONYM data. See the new readme for more details and I hope this helps.

**Comment by red0orange** [comment]
Thank you for your contribution!
